### ISSUE TITLE
Not so issus but some help needed

### ISSUE THREAD

**Issue by cvelele** [dudintv/vizartist-scripts#3]
I search all your scripts and didn't find similar to "advanced counter". I try to make some custom graphic bar and advanced counter plugin is not so flexible about displaying all sorts of information. Because of format mask (####.##) I can not sometimes write whole number like 70 and other time 70.2 or 70.25. You have to in advance format your display, with no  decimals, with one, with two ... Is there a work around or any suggestion about it?
Thx

**Comment by dudintv** [comment]
@cvelele Hi, just noticed your message.
I think we don't need to script this. Did you try change the Counter Mask by Parameter Control with parameter `FUNCTION*Advanced_Counter*inpmask`?

**Comment by dudintv** [comment]
![2022-11-20_00-33-22](https://user-images.githubusercontent.com/951452/202875724-b2312322-6638-42d3-a2a4-7362700f79f2.png)

**Comment by cvelele** [comment]
Ha ha, excellent.
Very elegant solution.
Thx again.

**Comment by cvelele** [comment]
What this inpmask mean?

**Comment by dudintv** [comment]
@cvelele `inpmask` is "console name" of the "Format mask" parameter of the AdvancedCounter plugin.

![2022-11-22_20-00-43](https://user-images.githubusercontent.com/951452/203399024-f0b2e483-babc-44d1-90a3-30e4ce163e48.png)

**Comment by cvelele** [comment]
So this mean, replace mask from Advanced Counter with plain text?

**Comment by dudintv** [comment]
@cvelele hm... Actually the mask is a plain text string, like that: "##.##". 
You can define this mask by typing this "#" symbols and "." period as a normal one line text.

So, we don't replace it. We just expose the mask as a text parameter for the outside control from PIlot/Trio/etc...

**Comment by cvelele** [comment]
Ok, thx.
