### ISSUE TITLE
Autofollow script help needed

### ISSUE THREAD

**Issue by cvelele** [dudintv/vizartist-scripts#4]
I needed help about you viz artist autofollow script. Write you some time ago about other script.

Script is working fine. But need little tweak.

If I have a cube, and another cube right below (stacked), when I move above cube up for 100 units below cube move down for 100 units. Same as left and right (like to mirror movement). Also if it is possible for a rotation, and the scale should follow the same scale as original.

I try with standard autofollow plugin and some control and didn't make it. Don`t know to write script so if you could help me would be awesome.

Thx

**Comment by dudintv** [comment]
Sorry, I've just noticed your comment.

I assume you need another my script — LinkTree:  https://github.com/dudintv/vizartist-scripts/tree/master/dudin-link/dudin-link-tree

Autofollow just follows by postition. But the LinkTree can duplicate all basic parameters from one subtree to another one based on containers names.

**Comment by cvelele** [comment]
Its ok, I was at another project. But this is it, thx again.
